### ISSUE TITLE
I found this useful for a landing page

### ISSUE THREAD

**Issue by eddiejaoude** [OpenSourceAtoZ/awesome-opensource#1]
I wasn't sure where you would want to include information like this? @rapidexpert 

http://yourlandingpagesucks.com/startup-landing-page-teardown-yc/?ref=quuu&utm_content=buffer680c5&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by rapidexpert** [comment]
I ❤️ the link. 

It would be great if we could apply the lessons in it to make a superb landing page for this github org!
Can we try this
- [x] create the repo for the org so it can have a landing page
- [ ] Create a prototype, Might be easier if we talk about look and feel offline? 
- [ ] enhance the github tutorial for designing effective webpages hosted on github via the gh-pages branch?

**Comment by eddiejaoude** [comment]
> enhance the github tutorial for designing effective webpages hosted on github via the gh-pages branch?

I think we need a separate one focusing on **GitHub Pages**

**Comment by rapidexpert** [comment]
It depends.. 😉 Can we try the practical approach? i.e. add issues to the github.io repo for this org as we plan and execute the page, once we can see how much useful content we can share, we can determine if it warrants an exclusive repo.

**Comment by eddiejaoude** [comment]
I thought you said the GitHub tutorial repo was already too big?

**Comment by rapidexpert** [comment]
Yes, however we also have some feedback from survey I sent out, which I'd recommend we review to see whether we want to enhance content/narrative on release 1 ( 23March presentatiion!) Hope you don't mind that I close this, as we are going off topic. Let's talk about it on slack/ hangout/ F2F.
